language: node_js
node_js:
  - "6"

sudo: false

addons:
  apt:
    packages:
    - libjansson-dev
    - libevent-dev


script:
  - node --version
  - apt-cache show libjansson-dev
  - apt-cache show libevent-dev
